$(document).ready(function(){
	$("#button1").click(function(){
		$(".button1").slideToggle();
	});
	$("#button2").click(function(){
		$(".button2").slideToggle();
	});
	$("#button3").click(function(){
		$(".button3").slideToggle();
	});
	$("#button4").click(function(){
		$(".button4").slideToggle();
	});
});